name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run tests
        run: bash test_all.sh --auto-rerun-failed

  build-and-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install epoll-shim
        run: brew install epoll-shim

      - name: Build
        run: make

      - name: Run tests
        run: bash test_all.sh --auto-rerun-failed
